### PR TITLE
Fix minor typo

### PR DESCRIPTION
**Pull request by ElleryW**
Fix minor typo.  Pleace is a bit outdated and by "a bit" I mean a few centuries...

### CODE REVIEW

**Comment by TheTypoMaster** [comment]
Omg. Thanks, why haven't I noticed this earlier? Merged!

**Comment by ElleryW** [comment]
You could say it was a no-brainer ;)

**Comment by ElleryW** [comment]
I apologize for that weak pun

**Comment by TheTypoMaster** [comment]
Hahaha, good pun

**Pull request merged**
